[bell]
animation = "EaseOutExpo"
duration = 0

[colors.bright]
black = "#828482"
blue = "#5ca7e4"
cyan = "#00c990"
green = "#1cad3c"
magenta = "#afb0ff"
red = "#c03545"
white = "#b0b0b0"
yellow = "#ffe914"

[colors.normal]
black = "#24292e"
blue = "#5a93ff"
cyan = "#08916a"
green = "#1cad3c"
magenta = "#6f42c1"
red = "#db524e"
white = "#d0d0d0"
yellow = "#c59000"

[colors.primary]
background = "#ffffff"
foreground = "#24292e"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
# gtk_theme_variant = "None"
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 120
lines = 42
